-- Diagnóstico de migraciones aplicadas.
-- Pégalo en phpMyAdmin (pestaña SQL) sobre la base de datos del proyecto.
-- Cada fila dice si la migración ya está aplicada (mirando si su columna/tabla existe).
SELECT m.migracion, IF(m.existe > 0, '✅ aplicada', '❌ FALTA') AS estado FROM (
  SELECT 'pedidos_kds.sql            (pedidos.origen)'            AS migracion, COUNT(*) existe FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='pedidos'      AND column_name='origen'
  UNION ALL SELECT 'inventario.sql             (tabla insumos)',          COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='insumos'
  UNION ALL SELECT 'inventario_b.sql           (pedidos.stock_descontado)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='pedidos'      AND column_name='stock_descontado'
  UNION ALL SELECT 'inventario_c.sql           (tabla proveedores)',     COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='proveedores'
  UNION ALL SELECT 'permisos.sql               (users.permissions)',     COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='users'        AND column_name='permissions'
  UNION ALL SELECT 'reservas.sql               (tabla reservas)',        COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='reservas'
  UNION ALL SELECT 'landing_tipo.sql           (landing_links.tipo)',    COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='landing_links' AND column_name='tipo'
  UNION ALL SELECT 'pos_arqueo.sql             (pos_turnos.ingreso_efectivo)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='pos_turnos' AND column_name='ingreso_efectivo'
  UNION ALL SELECT 'cartas_badges.sql          (carta_items.badges)',    COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='carta_items'  AND column_name='badges'
  UNION ALL SELECT 'ubicaciones_cerrado.sql    (ubicaciones.cerrado_manual)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ubicaciones' AND column_name='cerrado_manual'
  UNION ALL SELECT 'ubicaciones_horario.sql    (ubicaciones.hora_apertura)',  COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ubicaciones' AND column_name='hora_apertura'
  UNION ALL SELECT 'agenda.sql                 (tabla agenda)',          COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='agenda'
  UNION ALL SELECT 'agenda_bloquea.sql         (agenda.bloquea)',        COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='agenda'       AND column_name='bloquea'
  UNION ALL SELECT 'agenda_rango.sql           (agenda.fecha_fin)',      COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='agenda'       AND column_name='fecha_fin'
  UNION ALL SELECT 'nubefact.sql               (pedidos.comprobante_estado)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='pedidos' AND column_name='comprobante_estado'
  UNION ALL SELECT 'nubefact_email.sql         (pedidos.cliente_email)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='pedidos'      AND column_name='cliente_email'
  UNION ALL SELECT 'multilocal_facturacion.sql (ubicaciones.serie_boleta)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ubicaciones' AND column_name='serie_boleta'
  UNION ALL SELECT '41 sales_mode_ambos        (ubicaciones.sales_mode=ambos)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ubicaciones' AND column_name='sales_mode' AND COLUMN_TYPE LIKE '%ambos%'
  UNION ALL SELECT '42 asistencia              (tabla empleados)',         COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='empleados'
  UNION ALL SELECT '43 asistencia_pin_lockout  (empleados.pin_bloqueado_hasta)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='empleados'   AND column_name='pin_bloqueado_hasta'
  UNION ALL SELECT '44 insumo_tipo/receta_mod  (insumos.tipo)',            COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='insumos'     AND column_name='tipo'
  UNION ALL SELECT '45 eventos                 (tabla eventos)',           COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='eventos'
  UNION ALL SELECT '46 evento_dias             (tabla evento_dias)',       COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='evento_dias'
  UNION ALL SELECT '47 evento_truck            (eventos.truck_ubicacion_id)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='eventos'   AND column_name='truck_ubicacion_id'
  UNION ALL SELECT '48 evento_gastos           (tabla evento_gastos)',     COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='evento_gastos'
  UNION ALL SELECT '49 almacen_central         (ubicaciones.es_almacen)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ubicaciones' AND column_name='es_almacen'
  UNION ALL SELECT '50 quotes_evento           (quotes.evento_atendido)', COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='quotes' AND column_name='evento_atendido'
  UNION ALL SELECT '51 agenda_atendido         (agenda.atendido)',        COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='agenda' AND column_name='atendido'
  UNION ALL SELECT '52 quotes_venta            (quotes.venta_real)',      COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='quotes' AND column_name='venta_real'
  UNION ALL SELECT '53 agenda_venta            (agenda.venta_real)',      COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='agenda' AND column_name='venta_real'
  UNION ALL SELECT '54 eventos_usa_pos         (eventos.usa_pos)',        COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='eventos' AND column_name='usa_pos'
  UNION ALL SELECT '55 gastos_v2              (gastos.origen)',          COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='gastos' AND column_name='origen'
  UNION ALL SELECT '56 mesas                  (tabla mesa_pisos)',        COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='mesa_pisos'
  UNION ALL SELECT '57 cuentas                 (tabla cuentas)',           COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='cuentas'
  UNION ALL SELECT '58 cobro_mesas             (tabla cuenta_pagos)',      COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='cuenta_pagos'
  UNION ALL SELECT '59 cuenta_mesas             (tabla cuenta_mesas)',      COUNT(*) FROM information_schema.tables  WHERE table_schema=DATABASE() AND table_name='cuenta_mesas'
) m;
